"""
Step 7: Refresh the wiki's cross-reference indexes.

Regenerates wiki/topics/index.md and wiki/sources/index.md (both public pages — a colleague
browsing the site, not a maintenance tool) plus wiki/topics/DEDUP_INDEX.md (a maintainer-only
page, excluded from the Jekyll build via _config.yml, that carries the "what does each topic
already cite" detail an agent needs before adding a new source). It does not call an LLM or touch
topic/source content — it only reflects links and frontmatter that are already there.

Run this after authoring or updating any topic page (see wiki/AGENT_INSTRUCTIONS.md, update
workflow step 5-6). Check wiki/topics/DEDUP_INDEX.md — not the public topics/index.md — before
adding a new source, per that workflow.
"""
import glob
import os
import re
from collections import defaultdict

# Mirrors config.WIKI_SOURCES_DIR / config.WIKI_TOPICS_DIR. Not imported from config.py directly
# to avoid pulling in that module's langchain_community dependency for a two-constant read.
WIKI_SOURCES_DIR = os.path.join("wiki", "sources")
WIKI_TOPICS_DIR = os.path.join("wiki", "topics")

CITATION_RE = re.compile(r"\]\(\.\./sources/([^)]+\.md)\)")


def parse_frontmatter(text: str) -> dict:
    """Minimal YAML-frontmatter reader: handles `key: value` and folded (`>`) block scalars,
    which is all this wiki's frontmatter uses. Avoids a PyYAML dependency for a two-field read."""
    if not text.startswith("---"):
        return {}
    end = text.index("\n---", 3)
    lines = text[3:end].split("\n")
    data = {}
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or ":" not in line:
            i += 1
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if val == ">":
            i += 1
            parts = []
            while i < len(lines) and (lines[i].startswith("  ") or not lines[i].strip()):
                if lines[i].strip():
                    parts.append(lines[i].strip())
                i += 1
            data[key] = " ".join(parts)
            continue
        data[key] = val.strip('"')
        i += 1
    return data


# Non-source/non-topic .md files that live alongside the real pages in these two directories and
# must be skipped when globbing for pages: index.md/DEDUP_INDEX.md are generated by this script,
# ENRICHMENT_LOG.md is a hand-maintained tracker for the source-summary-enrichment task (see
# wiki/sources/ENRICHMENT_LOG.md) — none of these are themselves a source or topic page.
_GENERATED_INDEX_FILES = {"index.md", "DEDUP_INDEX.md", "ENRICHMENT_LOG.md"}

# Mirrors transportenvironment.org's own top-nav order, so the public topics/index.md groups
# subjects the same way a colleague already expects from the live site rather than an invented
# taxonomy. Sections with no wiki topic page yet (Vans, Buses, Rail, Batteries, Air Quality, Clean
# Cities as of this writing) are simply skipped below, not printed as empty headings — this list
# is deliberately longer than what the wiki currently covers so newly-sectioned topic pages sort
# correctly without reordering this list. A topic page missing a `section` field, or using one not
# listed here, falls into "Other", which sorts last — treat that as a prompt to either add the
# field or (if it's a genuinely new T&E top-level topic) add it to this list.
SECTION_ORDER = [
    "Cars & Vans", "Trucks", "Vans", "Buses", "Planes", "Ships", "Rail", "Batteries",
    "Energy & Fuels", "Sustainable Finance", "Air Quality", "Climate Instruments",
    "Green Steel", "Clean Cities",
    # "Mobility" is a wiki-only addition, not a real transportenvironment.org top-nav section —
    # see wiki/AGENT_INSTRUCTIONS.md's "Section" subsection for why. Kept last so it doesn't
    # disturb the real site's own nav order above.
    "Mobility",
]


def _section_sort_key(section):
    try:
        return (0, SECTION_ORDER.index(section))
    except ValueError:
        return (1, section)


def _load(dir_path):
    entries = {}
    for path in sorted(glob.glob(os.path.join(dir_path, "*.md"))):
        filename = os.path.basename(path)
        if filename in _GENERATED_INDEX_FILES:
            continue
        text = open(path, encoding="utf-8").read()
        entries[filename] = {"frontmatter": parse_frontmatter(text), "body": text}
    return entries


def refresh():
    topics = _load(WIKI_TOPICS_DIR)
    sources = _load(WIKI_SOURCES_DIR)

    cited_by = defaultdict(list)  # source filename -> [topic filenames]
    for t_filename, t in topics.items():
        cites = list(dict.fromkeys(CITATION_RE.findall(t["body"])))  # dedup, keep order
        t["cites"] = cites
        for s_filename in cites:
            cited_by[s_filename].append(t_filename)

    # — topics/index.md (public: grouped by Section — mirrors transportenvironment.org's own
    # top-nav topics, per wiki/AGENT_INSTRUCTIONS.md, rather than one flat list) —
    topics_path = os.path.join(WIKI_TOPICS_DIR, "index.md")
    ordered_topics = sorted(
        topics.items(), key=lambda kv: kv[1]["frontmatter"].get("first_seen", "")
    )
    sections = defaultdict(list)
    for filename, t in ordered_topics:
        sections[t["frontmatter"].get("section", "Other")].append((filename, t))
    with open(topics_path, "w", encoding="utf-8") as f:
        f.write("---\ntitle: Topics\n---\n\n# Topics\n\n")
        f.write(
            "<!-- Everything T&E works on that this wiki covers, one page per subject, grouped to "
            "match transportenvironment.org's own top-level topics — so \"where would this live "
            "on the real site\" and \"where does it live in this wiki\" are the same question. -->\n\n"
        )
        f.write("T&E's work, organized by subject. Each page tracks how T&E's position or "
                "estimates have evolved over time, with every claim linked back to the "
                "publication it's drawn from.\n\n")
        for section in sorted(sections, key=_section_sort_key):
            f.write(f"## {section}\n\n")
            f.write("| Topic | Summary |\n")
            f.write("|---|---|\n")
            for filename, t in sections[section]:
                fm = t["frontmatter"]
                title = fm.get("title", filename)
                summary = fm.get("summary", "")
                f.write(f"| [{title}]({filename}) | {summary} |\n")
            f.write("\n")
    print(f"Wrote {topics_path}  ({len(topics)} topics, {len(sections)} sections)")

    # — topics/DEDUP_INDEX.md (maintainer-only, excluded from the Jekyll build) —
    dedup_path = os.path.join(WIKI_TOPICS_DIR, "DEDUP_INDEX.md")
    with open(dedup_path, "w", encoding="utf-8") as f:
        f.write("---\ntitle: Topic dedup index (maintainer-only, not published)\n---\n\n")
        f.write("# Topic dedup index\n\n")
        f.write("Check this table before adding a new source: it shows what each topic already "
                "covers and which sources it cites, so you know which pages might need updating "
                "rather than duplicating. This page is excluded from the built site (see "
                "`_config.yml`) — it's a maintenance tool, not a reader-facing page.\n\n")
        f.write("| Topic | Section | Type | Summary | Sources cited | First seen | Last updated |\n")
        f.write("|---|---|---|---|---|---|---|\n")
        for filename, t in ordered_topics:
            fm = t["frontmatter"]
            title = fm.get("title", filename)
            summary = fm.get("summary", "")
            cite_links = ", ".join(
                f"[{sources.get(c, {}).get('frontmatter', {}).get('title', c)}](../sources/{c})"
                for c in t["cites"]
            )
            f.write(
                f"| [{title}]({filename}) | {fm.get('section', '')} | {fm.get('type', '')} "
                f"| {summary} | {cite_links} "
                f"| {fm.get('first_seen', '')} | {fm.get('last_updated', '')} |\n"
            )
    print(f"Wrote {dedup_path}  ({len(topics)} topics)")

    # — sources/index.md (public) —
    sources_path = os.path.join(WIKI_SOURCES_DIR, "index.md")
    ordered_sources = sorted(
        sources.items(), key=lambda kv: kv[1]["frontmatter"].get("date", "") or ""
    )
    with open(sources_path, "w", encoding="utf-8") as f:
        f.write("---\ntitle: Sources\n---\n\n")
        f.write(f"# Sources ({len(sources)})\n\n")
        f.write("Every T&E publication cited anywhere in this wiki. Open a source page for a "
                "link to the original publication.\n\n")
        f.write("| Source | Date | Cited by topics |\n")
        f.write("|---|---|---|\n")
        for filename, s in ordered_sources:
            fm = s["frontmatter"]
            title = fm.get("title", filename)
            date = (fm.get("date", "") or "")[:10]
            citing_topics = ", ".join(
                f"[{topics[t]['frontmatter'].get('title', t)}](../topics/{t})"
                for t in cited_by.get(filename, [])
            ) or "*(none yet)*"
            f.write(f"| [{title}]({filename}) | {date} | {citing_topics} |\n")
    print(f"Wrote {sources_path}  ({len(sources)} sources)")


if __name__ == "__main__":
    refresh()
